# Generated by Django 3.0.6 on 2020-06-28 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='pofile_pic',
            new_name='profile_pic',
        ),
    ]
